server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:Lqw-Coder/springcloud-config.git
          search-paths:
            - springcloud-config
          uri: https://github.com/Lqw-Coder/springcloud-config.git
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka